# Generated by Django 4.1 on 2023-04-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vw_app', '0007_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
